apiVersion: v1
kind: Service
metadata:
  name: mcp-kubernetes-svc
  labels:
    app: mcp-kubernetes
spec:
  selector:
    app: mcp-kubernetes
  ports:
    - protocol: TCP
      port: 80             # service port
      targetPort: 8080     # same as containerPort
  type: ClusterIP     
