apiVersion: v1
kind: Service
metadata:
  name: lightspeed-core
  labels:
    app: lightspeed-core
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: lightspeed-core-tls
spec:
  selector:
    app: lightspeed-core
  ports:
  - name: http
    port: 8443
    targetPort: 8443
    protocol: TCP
  type: ClusterIP
